jobs:
- job: macOS_x86_64_Clang_Release
  timeoutInMinutes: 180
  pool:
    vmImage: 'macOS-11'
  steps:
  - bash: |
      set -e

      curl -o "$(Agent.TempDirectory)/sde.tar.xz" -L $(SDE_URL_MACOS3)
      mkdir -p "$(Agent.TempDirectory)/sde-bin"
      tar -C "$(Agent.TempDirectory)/sde-bin" -xJf "$(Agent.TempDirectory)/sde.tar.xz" --strip 1
      export PATH=$PATH:$(Agent.TempDirectory)/sde-bin
      sde64 -help || true

      sudo security authorizationdb write system.privilege.taskport allow

      sde64 -chip_check_exe_only -- $(Agent.TempDirectory)/sde-bin/intel64/nullapp

      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer"
      brew install ninja
      ci/run.sh build-release -DKFR_USE_SDE=ON -DKFR_ARCH=sse2 -DKFR_ENABLE_DFT_MULTIARCH=ON -DCMAKE_BUILD_TYPE=Release      
