jobs:
- job: macOS_x86_64_Clang_Release
  timeoutInMinutes: 180
  strategy:
    matrix:
      xcode11:
        XCODE_VER: 13.2.1
      xcode10:
        XCODE_VER: 12.5.1
  pool:
    vmImage: 'macOS-11'
  steps:
  - bash: |
      set -e

      curl -o "$(Agent.TempDirectory)/sde.tar.xz" -L $(SDE_URL_MACOS3)
      mkdir -p "$(Agent.TempDirectory)/sde-bin"
      tar -C "$(Agent.TempDirectory)/sde-bin" -xJf "$(Agent.TempDirectory)/sde.tar.xz" --strip 1
      export PATH=$PATH:$(Agent.TempDirectory)/sde-bin
      sde64 -help || true

      sudo security authorizationdb write system.privilege.taskport allow

      sde64 -chip_check_exe_only -- $(Agent.TempDirectory)/sde-bin/intel64/nullapp

      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_$(XCODE_VER).app/Contents/Developer"
      brew install ninja
      ci/run.sh build-release -DKFR_ENABLE_CAPI_BUILD=ON -DKFR_USE_SDE=ON -DKFR_ARCH_TESTS=avx2 -DKFR_ARCH=sse2 -DKFR_ENABLE_DFT_MULTIARCH=ON -DCMAKE_BUILD_TYPE=Release      
